"""empty message

Revision ID: a19c8354f6d3
Revises: 
Create Date: 2020-12-05 22:32:04.480021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19c8354f6d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asst_name'), 'asst', ['name'], unique=True)
    op.create_table('locl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locl_ip'), 'locl', ['ip'], unique=True)
    op.create_index(op.f('ix_locl_name'), 'locl', ['name'], unique=True)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_name'), 'type', ['name'], unique=True)
    op.create_table('asstLocl',
    sa.Column('id_asst', sa.Integer(), nullable=True),
    sa.Column('id_locl', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_asst'], ['asst.id'], ),
    sa.ForeignKeyConstraint(['id_locl'], ['locl.id'], )
    )
    op.create_table('elem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_asst', sa.Integer(), nullable=True),
    sa.Column('id_locl', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=4), nullable=True),
    sa.Column('nameFull', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_asst'], ['asst.id'], ),
    sa.ForeignKeyConstraint(['id_locl'], ['locl.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elem_name'), 'elem', ['name'], unique=False)
    op.create_index(op.f('ix_elem_nameFull'), 'elem', ['nameFull'], unique=True)
    op.create_index(op.f('ix_elem_value'), 'elem', ['value'], unique=False)
    op.create_table('bindElem',
    sa.Column('id_folr', sa.Integer(), nullable=True),
    sa.Column('id_fold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_fold'], ['elem.id'], ),
    sa.ForeignKeyConstraint(['id_folr'], ['elem.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bindElem')
    op.drop_index(op.f('ix_elem_value'), table_name='elem')
    op.drop_index(op.f('ix_elem_nameFull'), table_name='elem')
    op.drop_index(op.f('ix_elem_name'), table_name='elem')
    op.drop_table('elem')
    op.drop_table('asstLocl')
    op.drop_index(op.f('ix_type_name'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_locl_name'), table_name='locl')
    op.drop_index(op.f('ix_locl_ip'), table_name='locl')
    op.drop_table('locl')
    op.drop_index(op.f('ix_asst_name'), table_name='asst')
    op.drop_table('asst')
    # ### end Alembic commands ###
